#############################################################################
# Makefile for building: networking
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  networking.pro
# Template: subdirs
# Command: C:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin/qmake.exe -o Makefile networking.pro -spec win32-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-protocol \
		sub-client \
		sub-server


sub-protocol-qmake_all:  FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler
	cd protocol/ && $(MAKE) -f Makefile qmake_all
sub-protocol: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile
sub-protocol-make_first: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile 
sub-protocol-all: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile all
sub-protocol-clean: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile clean
sub-protocol-distclean: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile distclean
sub-protocol-install_subtargets: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile install
sub-protocol-uninstall_subtargets: FORCE
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile uninstall
sub-client-qmake_all:  FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler
	cd client/ && $(MAKE) -f Makefile qmake_all
sub-client: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile
sub-client-make_first: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile 
sub-client-all: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile all
sub-client-clean: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile clean
sub-client-distclean: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile distclean
sub-client-install_subtargets: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile install
sub-client-uninstall_subtargets: FORCE
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile uninstall
sub-server-qmake_all:  FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler
	cd server/ && $(MAKE) -f Makefile qmake_all
sub-server: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile
sub-server-make_first: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile 
sub-server-all: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile all
sub-server-clean: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile clean
sub-server-distclean: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile distclean
sub-server-install_subtargets: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile install
sub-server-uninstall_subtargets: FORCE
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile uninstall

Makefile: networking.pro ../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf ../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/spec_pre.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/qdevice.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/device_config.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/sanitize.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/gcc-base.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/g++-base.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/angle.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/windows-vulkan.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/g++-win32.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/qconfig.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qt_functions.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qt_config.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/toolchain.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/default_pre.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/win32/default_pre.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/resolve_config.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/default_post.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/resources.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qtquickcompiler.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/precompile_header.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/warn_on.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qmake_use.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/file_copies.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/win32/windows.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exceptions.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/yacc.prf \
		../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/lex.prf \
		networking.pro
	$(QMAKE) -o Makefile networking.pro -spec win32-g++ CONFIG+=qtquickcompiler
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/spec_pre.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/qdevice.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/device_config.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/sanitize.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/gcc-base.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/g++-base.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/angle.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/windows-vulkan.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/common/g++-win32.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/qconfig.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qt_functions.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qt_config.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/toolchain.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/default_pre.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/win32/default_pre.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/resolve_config.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/default_post.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/resources.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qtquickcompiler.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/precompile_header.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/warn_on.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/qmake_use.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/file_copies.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/win32/windows.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/testcase_targets.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/exceptions.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/yacc.prf:
../../../Qt/Qt5.12.0/5.12.0/mingw73_64/mkspecs/features/lex.prf:
networking.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile networking.pro -spec win32-g++ CONFIG+=qtquickcompiler

qmake_all: sub-protocol-qmake_all sub-client-qmake_all sub-server-qmake_all FORCE

make_first: sub-protocol-make_first sub-client-make_first sub-server-make_first  FORCE
all: sub-protocol-all sub-client-all sub-server-all  FORCE
clean: sub-protocol-clean sub-client-clean sub-server-clean  FORCE
distclean: sub-protocol-distclean sub-client-distclean sub-server-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-protocol-install_subtargets sub-client-install_subtargets sub-server-install_subtargets FORCE
uninstall_subtargets: sub-protocol-uninstall_subtargets sub-client-uninstall_subtargets sub-server-uninstall_subtargets FORCE

sub-protocol-debug:
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile debug
sub-client-debug:
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile debug
sub-server-debug:
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile debug
debug: sub-protocol-debug sub-client-debug sub-server-debug

sub-protocol-release:
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile release
sub-client-release:
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile release
sub-server-release:
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile release
release: sub-protocol-release sub-client-release sub-server-release

sub-protocol-check:
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile check
sub-client-check:
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile check
sub-server-check:
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile check
check: sub-protocol-check sub-client-check sub-server-check

sub-protocol-benchmark:
	@test -d protocol/ || mkdir -p protocol/
	cd protocol/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/protocol/protocol.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile benchmark
sub-client-benchmark:
	@test -d client/ || mkdir -p client/
	cd client/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/client/client.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile benchmark
sub-server-benchmark:
	@test -d server/ || mkdir -p server/
	cd server/ && ( test -e Makefile || $(QMAKE) -o Makefile C:/Practicas_ULL/SOA/networking/server/server.pro -spec win32-g++ CONFIG+=qtquickcompiler ) && $(MAKE) -f Makefile benchmark
benchmark: sub-protocol-benchmark sub-client-benchmark sub-server-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

